EAutoSkola/Controllers/VozilaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using EAutoSkola.Models;
using EAutoSkola.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using EAutoSkola.Models.Repository;
using ReflectionIT.Mvc.Paging;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace EAutoSkola.Controllers
{
    [Authorize(Roles = "Referent")]
    public class VozilaController : Controller
    {
        private readonly IvozilaRepository reposVozila;
        private readonly IKategorijaRepository reposKategorije;
        private static IWebHostEnvironment _hostingEnvironment;
        private readonly ITerminRasporedaCasova reposTerminRasporedC;




        public VozilaController(IvozilaRepository reposVozila, 
            IKategorijaRepository reposKategorije,
            IWebHostEnvironment hostEnvironment,
            ITerminRasporedaCasova reposTerminRasporedC)
        {
            this.reposTerminRasporedC = reposTerminRasporedC;
            this.reposVozila = reposVozila;
            this.reposKategorije = reposKategorije;
            _hostingEnvironment = hostEnvironment;
           

        }
        public IActionResult EvidentirajVoziloForm()
        {

            List<Kategorija> kategorije = reposKategorije.GetAll(); /*baza.Kategorije.ToList();*/
            DefaultViewModel kategorijeVM = new DefaultViewModel()
            {
                Kategorije = kategorije
            };
            return View(kategorijeVM);
        }
        [AllowAnonymous]
        public async Task<IActionResult> PrikaziVozila(int page=1)
        {

           var vozila = reposVozila.GetVozila(); /*baza.Vozila.Include(s => s.Kategorija).ToList();*/
            
            var model = await PagingList.CreateAsync<Vozilo>(vozila, 4, page);
            model.Action = "PrikaziVozila";
            return View(model);
        }
        public IActionResult DodajVozilo(DefaultViewModel voziloModel, int VoziloId)
        {

            Vozilo v;
            if (VoziloId == 0)
            {
                v = new Vozilo();

                //Slika
                string uniqueFileName = null;


                if (voziloModel.Photo != null)
                {
                    string _path = voziloModel.Photo.FileName;
                    string _imeExtenzija = System.IO.Path.GetFileName(_path);
                    string uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images");
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + _imeExtenzija;
                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                    voziloModel.Photo.CopyTo(new FileStream(filePath, FileMode.Create));

                }
                v.GodinaProizvodnje = voziloModel.GodinaProizvodnje;
                v.Model = voziloModel.Model;
                v.Marka = voziloModel.Marka;
                v.RegistarskaOznaka = voziloModel.RegOznaka;
                v.KategorijaId = voziloModel.KategorijaId;
                v.PhotoPath = uniqueFileName;
                reposVozila.Add(v);
            }
            else
            {
                v = reposVozila.GetById(voziloModel.VoziloId); /*baza.Vozila.Find(voziloModel.VoziloId);*/
                v.GodinaProizvodnje = voziloModel.GodinaProizvodnje;
                v.Model = voziloModel.Model;
                v.Marka = voziloModel.Marka;
                v.RegistarskaOznaka = voziloModel.RegOznaka;
                v.KategorijaId = voziloModel.KategorijaId;
                reposVozila.Save();
            }
            return RedirectToAction(nameof(PrikaziVozila));
        }
        public IActionResult UrediVoziloForm(int VoziloId)
        {

            Vozilo g = reposVozila.GetById(VoziloId);/* baza.Vozila.Find(VoziloId);*/
            List<Kategorija> kategorije = reposKategorije.GetAll(); /*baza.Kategorije.ToList();*/
            DefaultViewModel voziloVM = new DefaultViewModel()
            {
                Vozilo = g,
                Kategorije = kategorije
            };
            return View(voziloVM);
        }
        public IActionResult ObrisiVozilo(int VoziloId)
        {
            if (reposTerminRasporedC.Vozilo(VoziloId)==true) return View("Alert");
            Vozilo pronadjenoVozilo = reposVozila.GetById(VoziloId);/*baza.Vozila.Find(VoziloId);*/
            if (pronadjenoVozilo != null)
            {
                reposVozila.Remove(pronadjenoVozilo);
                //baza.Remove(pronadjenoVozilo);
               
            }
            else
            {
                return Content("Vozilo ne postoji u bazi!");
            }

            return RedirectToAction("PrikaziVozila");
        }
        public IActionResult DetaljiVozila(int VoziloId)
        {
            Vozilo vozilo = reposVozila.GetByIdWithInclude(VoziloId); /*baza.Vozila.Include(s => s.Kategorija).Where(s => s.Id == VoziloId).SingleOrDefault();*/
            VozilaDetaljiViewModel vozilaDetalji = new VozilaDetaljiViewModel
            {
                Vozilo = vozilo
            };
            return View(vozilaDetalji);
        }
    }
}

EAutoSkola/Views/Vozila/DetaljiVozila.cshtml
@model EAutoSkola.ViewModel.VozilaDetaljiViewModel;
@{ 
 ViewBag.Title = "DetaljiVozila";
    var photoPath = "~/Images/" + (Model.Vozilo.PhotoPath ?? "noimage.jpg");
}

        <div class="spoljni">
            <h2>Detalji vozila</h2>
            <div class="detaljiVozila">
                <div id="divSlikaVozila">
                    <img src="@photoPath" asp-append-version="true" />
                </div>
                <div id="textDetaliVozila">
                    <h4><b>Model:</b>  @Model.Vozilo.Model</h4>
                    <h4><b>Marka:</b>  @Model.Vozilo.Marka</h4>
                    <h4><b>Godina proizvodnje:</b>  @Model.Vozilo.GodinaProizvodnje</h4>
                    <h4><b>Registarska oznaka:</b>  @Model.Vozilo.RegistarskaOznaka</h4>
                    <h4><b>Kategorija:</b>  @Model.Vozilo.Kategorija.Naziv</h4>
                </div>
               
            </div>
        </div>

EAutoSkola/Views/Vozila/EvidentirajVoziloForm.cshtml
@model EAutoSkola.ViewModel.DefaultViewModel;
@{
    ViewData["Title"] = "EvidentirajVoziloForm";
    Layout = "_LayoutReferent";
}
<div class="divForme">
    <h2>Evidentiraj vozilo</h2>
    <form enctype="multipart/form-data" asp-controller="Vozila" asp-action="DodajVozilo">

        <div class="form-group">
            <label>Godina proizvodnje</label>
            <input type="text" class="form-control" asp-for="GodinaProizvodnje">

        </div>
        <div class="form-group">
            <label>Marka automobila</label>
            <input type="text" class="form-control" asp-for="Marka">
        </div>
        <div class="form-group">
            <label>Model automobila</label>
            <input type="text" class="form-control" asp-for="Model">
        </div>
        <div class="form-group">
            <label>Registarska oznaka</label>
            <input type="text" class="form-control" asp-for="RegOznaka">
        </div>
        <div>
            <label>Odaberite kategoriju vozila</label>
            <select id="inputState" class="form-control" asp-for="KategorijaId">
                @foreach (var kate in @Model.Kategorije)
                {
                    <option value="@kate.Id">@kate.Naziv</option>
                }

            </select>
        </div><br />
        <div class="form-group">
            <div class="custom-file">
                <input asp-for="Photo" class="form-control custom-file-input">
                <label class="custom-file-label">Choose File...</label>
            </div>
        </div>
        <br /><br />
        <button type="submit" class="btn btn-primary">Sacuvaj</button>
        @section Scripts{
            <script>
                $(document).ready(function () {
                    $('.custom-file-input').on("change", function () {
                        var filename = $(this).val().split("\\").pop();
                        $(this).next('.custom-file-label').html(filename);
                    });
                });
            </script>

        }
    </form>
    </div>

EAutoSkola/Views/Vozila/PrikaziVozila.cshtml
@*@model EAutoSkola.ViewModel.DefaultViewModel;

    @{
        ViewData["Title"] = "PrikaziVozila";
        Layout = "_LayoutReferent";

    }*@
@model ReflectionIT.Mvc.Paging.PagingList<EAutoSkola.Models.Vozilo>
@using ReflectionIT.Mvc.Paging;
@addTagHelper *,ReflectioIT.Mvc.Paging

<html>
<head>
    <link href="~/css/PrikazVozila.css" type="text/css" rel="stylesheet" />
</head>

<body>
    <h2 style=" color: #f9f9f9;
    border: 2px solid #f9f9f9;
    padding: 10px;
    background-color: #00c6ff">
        Vozila
    </h2>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="carousel slide" id="myCarousel">
                    <div class="carousel-inner">
                        <div class="item active">
                            <ul class="thumbnails">
                                @foreach (var i in @Model)
                                {
                                    var photoPath = "~/Images/" + (@i.PhotoPath ?? "noimage.jpg");
                                    <li class="span3">
                                        <div class="thumbnail">
                                            <img class="card-img-top" src="@photoPath" asp-append-version="true" />
                                        </div>
                                        <div class="caption">
                                            <div class="card-footer text-center">
                                                <a asp-controller="Vozila" asp-action="DetaljiVozila" asp-route-VoziloId="@i.Id" class="btn btn-primary">Detalji</a>
                                                <a asp-controller="Vozila" asp-action="UrediVoziloForm" asp-route-VoziloId="@i.Id" class="btn btn-primary ">Uredi</a>
                                                <a asp-controller="Vozila" asp-action="ObrisiVozilo" asp-route-VoziloId="@i.Id" class="btn btn-danger ">Obrisi</a>
                                            </div>
                                        </div>
                                    </li>
                                }

                            </ul>

                        </div>



                    </div><!-- /#myCarousel -->

                </div><!-- /.span12 -->
            </div><!-- /.row -->
        </div><!-- /.container -->


    </div>
    <nav aria-label="Vozila navigation example">
        @await this.Component.InvokeAsync("Pager", new { PagingList = this.Model })
    </nav>
    <nav>
        <nav arial-label="Post Paging">
            <vc:pager paging-list="@Model" />
        </nav>
    </nav>

    <a asp-controller="Vozila" asp-action="EvidentirajVoziloForm" class="btn btn-primary">Dodaj vozilo</a>
</body>
</html>

EAutoSkola/Views/Vozila/UrediVoziloForm.cshtml
@model EAutoSkola.ViewModel.DefaultViewModel;
@{
    Layout = "_LayoutReferent";
}
<div class="divForme">
    <h2>UrediVoziloForm</h2>
    <form action="/Vozila/DodajVozilo">

        <input type="hidden" class="form-control" name="VoziloId" value="@Model.Vozilo.Id">
        <div class="form-group">
            <label>Godina proizvodnje</label>
            <input type="text" class="form-control" name="GodinaProizvodnje" value="@Model.Vozilo.GodinaProizvodnje">

        </div>
        <div class="form-group">
            <label>Marka automobila</label>
            <input type="text" class="form-control" name="Marka" value="@Model.Vozilo.Marka">
        </div>
        <div class="form-group">
            <label>Model automobila</label>
            <input type="text" class="form-control" name="Model" value="@Model.Vozilo.Model">
        </div>
        <div class="form-group">
            <label>Registarska oznaka</label>
            <input type="text" class="form-control" name="RegOznaka" value="@Model.Vozilo.RegistarskaOznaka">
        </div>
        <div>
            <label>Odaberite kategoriju vozila</label>
            <select id="inputState" class="form-control" name="KategorijaId">
                @foreach (var kate in @Model.Kategorije)
                {
                    @if (kate.Id == @Model.Vozilo.KategorijaId)
                    {
                        <option value="@kate.Id" selected="selected">@kate.Naziv</option>
                    }
                    else
                    {
                        <option value="@kate.Id">@kate.Naziv</option>
                    }

                }

            </select>

        </div><br /><br />

        <button type="submit" class="btn bg-primary">Sacuvaj</button>

        }
    </form>
    </div>