EAutoSkola/Controllers/UslugeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EAutoSkola.Models;
using EAutoSkola.Models.Repository;
using EAutoSkola.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EAutoSkola.Controllers
{
    [Authorize(Roles = "Referent")]
    public class UslugeController : Controller
    {
        private readonly IUslugeRepository reposUsluge;
        private readonly IKategorijaRepository reposKategorija;

        public UslugeController(IUslugeRepository reposUsluge,IKategorijaRepository reposKategorija)
        {
            this.reposUsluge = reposUsluge;
            this.reposKategorija = reposKategorija;
        }
        [AllowAnonymous]
        public IActionResult PrikaziUsluge()
        {

            List<Usluga> us = reposUsluge.GetAll();/*baza.Usluge.Include(s => s.Kategorija).ToList();*/
            var uslugeView = new UslugeViewModel
            {
                Usluge = us
            };
            return View(uslugeView);
        }
        public IActionResult DodajUsluguForm()
        {

            List<Kategorija> kat = reposKategorija.GetAll();/*baza.Kategorije.ToList();*/
            var kateg = new KategorijeViewModel
            {
                Kategorije = kat
            };
            return View(kateg);
        }
        public IActionResult DodajUslugu(string Naziv, string Opis, float Cijena, int KategorijaId)
        {

            Usluga u = new Usluga
            {
                Naziv = Naziv,
                Opis = Opis,
                Cijena = Cijena,
                KategorijaId = KategorijaId
            };
            reposUsluge.Add(u);

            return RedirectToAction("PrikaziUsluge");
        }
        public IActionResult ObrisiUslugu(int UslugaId)
        {

            Usluga u = reposUsluge.GetById(UslugaId); /*baza.Usluge.Find(UslugaId);*/
            if (u == null)
            {
                Content("Nepostojeca uplata!");
            }
            else
            {
                reposUsluge.Remove(u);
            }
            return RedirectToAction(nameof(PrikaziUsluge));
        }
        public IActionResult UrediUslugu(int UslugaId)
        {

            Usluga usluga = reposUsluge.GetById(UslugaId); /*baza.Usluge.Find(UslugaId);*/
            List<Kategorija> kategorije = reposKategorija.GetAll();
            UslugeViewModel uslugeVM = new UslugeViewModel()
            {
                Usluga = usluga,
                Kategorije = kategorije
            };
            return View(uslugeVM);
        }
        public IActionResult DodajUredjenuUslugu(int UslugaId, string Naziv, string Opis,int Cijena, int KategorijaId)
        {

            Usluga k = reposUsluge.GetById(UslugaId);/* baza.Usluge.Find(UslugaId);*/
            k.Naziv = Naziv;
            k.Opis = Opis;
            k.Cijena = Cijena;
            k.KategorijaId = KategorijaId;
            reposUsluge.Save();
           
            return RedirectToAction(nameof(PrikaziUsluge));
        }
    }
}

EAutoSkola/Views/Usluge/DodajUsluguForm.cshtml
@model EAutoSkola.ViewModel.KategorijeViewModel;
@{
    ViewBag.Title = "DodajUsluguForm";
    Layout = "_LayoutReferent";
}
<div class="divForme">
    <h2>Dodaj uslugu</h2>
    <form action="/Usluge/DodajUslugu">
        <div class="form-group">
            <label>Naziv usluge</label>
            <input type="text" class="form-control" name="Naziv">
        </div>
        <div class="form-group">
            <label>Opis</label>
            <input type="text" class="form-control" name="Opis">
        </div>
        <div class="form-group">
            <label>Cijena</label>
            <input type="text" class="form-control" name="Cijena">
        </div>
        <div class="form-group">
            <label>Odaberite kategoriju</label>
            <select class="form-control" name="KategorijaId">
                @foreach (var kategorije in Model.Kategorije)
                {
                    <option value="@kategorije.Id">@kategorije.Naziv</option>
                }
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Sacuvaj</button>
    </form>
    </div>

EAutoSkola/Views/Usluge/PrikaziUsluge.cshtml
@model EAutoSkola.ViewModel.UslugeViewModel;
@{
    ViewBag.Title = "PrikaziUsluge";
}

    <h2 style=" color: #f9f9f9;
    border: 2px solid #f9f9f9;
    padding: 10px;
    background-color: #00c6ff">
        Usluge
    </h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Naziv</th>
            <th scope="col">Opis</th>
            <th scope="col">Cijena</th>
            <th scope="col">Kategorija</th>
        </tr>
    </thead>

    @foreach (var usl in Model.Usluge)
    {
        <tbody>
            <tr>
                <td>@usl.Naziv</td>
                <td>@usl.Opis</td>
                <td>@usl.Cijena</td>
                <td>@usl.Kategorija.Naziv</td>
                <td><a asp-controller="Usluge" asp-action="UrediUslugu" asp-route-UslugaId="@usl.Id" class="btn btn-primary">Uredi</a></td>

                <td><a asp-controller="Usluge" asp-action="ObrisiUslugu" asp-route-UslugaId="@usl.Id" class="btn btn-danger">Obrisi</a></td>
            </tr>
        </tbody>
    }


</table>
<a asp-controller="Usluge" asp-action="DodajUsluguForm"class="btn btn-primary">Dodaj uslugu</a>

EAutoSkola/Views/Usluge/UrediUslugu.cshtml
@model EAutoSkola.ViewModel.UslugeViewModel;
@{
    ViewData["Title"] = "UrediUslugu";
    Layout = "_LayoutReferent";
}
<div class="divForme">
    <h2>UrediUslugu</h2>

    <form action="/Usluge/DodajUredjenuUslugu">
        <input type="hidden" class="form-control" name="UslugaId" value="@Model.Usluga.Id">
        <div class="form-group">
            <label>Naziv</label>
            <input type="text" class="form-control" name="Naziv" value="@Model.Usluga.Naziv">
        </div>
        <div class="form-group">
            <label>Opis</label>
            <input type="text" class="form-control" name="Opis" value="@Model.Usluga.Opis">
        </div>
        <div class="form-group">
            <label>Cijena</label>
            <input type="text" class="form-control" name="Cijena" value="@Model.Usluga.Cijena">
        </div>
        <div class="form-group">
            <label>Odaberite kategoriju</label>
            <select class="form-control" name="KategorijaId">
                @foreach (var kategorije in @Model.Kategorije)
                {
                    @if (Model.Usluga.KategorijaId == kategorije.Id)
                    {
                        <option value="@kategorije.Id" selected="selected">@kategorije.Naziv</option>
                    }
                    else
                    {
                        <option value="@kategorije.Id">@kategorije.Naziv</option>

                    }

                }
            </select>
        </div>
        <button type="submit" class="btn bg-primary">Sacuvaj</button>
    </form>
    </div>