EAutoSkola/Models/Plata.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EAutoSkola.Models
{
    public class Plata
    {
        public int Id { get; set; }
        public float Iznos { get; set; }
        
        public DateTime Datum { get; set; }
        public int UposlenikId { get; set; }
        public Uposlenik Uposlenik { get; set; }
    }
}

EAutoSkola/Controllers/PlataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EAutoSkola.Models;
using EAutoSkola.Models.Repository;
using EAutoSkola.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EAutoSkola.Controllers
{
    [Authorize(Roles = "Referent")]
    public class PlataController : Controller
    {
        private readonly IUposleniciRepository reposUposlenici;
        private readonly IPlataRepository reposPlata;

        public PlataController(IUposleniciRepository reposUposlenici, IPlataRepository reposPlata)
        {
            this.reposUposlenici = reposUposlenici;
            this.reposPlata = reposPlata;

        }
        public IActionResult EvidentirajPlatu()
        {
            List<Uposlenik> uposlenici = reposUposlenici.GetAll();
            PlataViewModel plateVM = new PlataViewModel {
                Uposlenici = uposlenici
            };
            return View(plateVM);
        }
        public IActionResult SnimiPlatu(int PlataId,int Iznos, DateTime Datum, int UposlenikId)
        {
            if (PlataId == 0)
            {
                Plata novaPlata = new Plata
                {
                    Iznos = Iznos,
                    Datum = Datum,
                    UposlenikId = UposlenikId
                };
                reposPlata.Add(novaPlata);
            }
            else
            {
                Plata p = reposPlata.GetById(PlataId);
                p.Datum = Datum;
                p.Iznos = Iznos;
                p.UposlenikId = UposlenikId;
                reposPlata.Save();
            }
            return RedirectToAction("PrikaziPlate");
        }
        public IActionResult PrikaziPlate()
        {
            List<Plata> plate = reposPlata.GetAll();
            var prikazPlata = new PlataViewModel {
                ListaPlata = plate
            };
            return View(prikazPlata);
        }
        public IActionResult UrediPlatu(int PlataId)
        {
           Plata pronadjenaPlata=reposPlata.GetById(PlataId);
            List<Uposlenik> uposlenici = reposUposlenici.GetAll();
            PlataViewModel plataVM = new PlataViewModel()
            {
              Plata=pronadjenaPlata,
              Uposlenici=uposlenici
            };
            return View(plataVM);
        }
       
    }
}

EAutoSkola/Views/Plata/EvidentirajPlatu.cshtml
@model EAutoSkola.ViewModel.PlataViewModel;
@{
    ViewData["Title"] = "EvidentiajPlatu";
    Layout = "_LayoutReferent";
}
<div class="divForme">
    <h2>Evidentiaj platu</h2>
    <form action="/Plata/SnimiPlatu" >
        <div class="form-group">
            <label>Iznos</label>
            <input type="text"  Name="Iznos"  class="form-control" >
        </div>
        <div class="form-group">
            <label>Datum</label>
            <input type="date"  Name="Datum"  class="form-control" >
        </div>
        <div class="form-group">
            <label>Uposlenik</label>
            <select class="form-control" Name="UposlenikId">
                @foreach (var uposlenici in @Model.Uposlenici)
                {
                    <option value="@uposlenici.Id">@uposlenici.ImePrezime</option>
                }
            </select>
        </div><br />

        <button type="submit" class="btn btn-primary">Sacuvaj</button>
    </form>
</div>

EAutoSkola/Views/Plata/PrikaziPlate.cshtml
@model EAutoSkola.ViewModel.PlataViewModel;

<h2 style=" color: #f9f9f9;
    border: 2px solid #f9f9f9;
    padding: 10px;
    background-color: #00c6ff">
    Plate
</h2>


<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Iznos</th>
            <th scope="col">Datum</th>
            <th scope="col">Uposlenik</th>
        </tr>
    </thead>

    @foreach (var i in @Model.ListaPlata)
    {
        <tbody>
          
            <tr>
                <td>@i.Iznos</td>
                <td>@Convert.ToDateTime(@i.Datum).ToString("dd/MM/yyyy")</td>
                <td>@i.Uposlenik.ImePrezime</td>
                <td><a asp-controller="Plata" asp-action="UrediPlatu" asp-route-PlataId="@i.Id" class="btn btn-primary">Izmjeni</a></td>
             </tr>
        </tbody>
    }
</table>

<a asp-controller="Plata" asp-action="EvidentirajPlatu" class="btn btn-primary">Evidentiraj platu</a>

EAutoSkola/Views/Plata/UrediPlatu.cshtml
@model EAutoSkola.ViewModel.PlataViewModel;

<div class="divForme">
    <h2>Uredite platu</h2>
    <form asp-action="SnimiPlatu">
        <input type="hidden" class="form-control" Name="PlataId" value="@Model.Plata.Id">
        <div class="form-group">
            <label>Iznos</label>
            <input type="text" class="form-control" Name="Iznos" value="@Model.Plata.Iznos">
        </div>
        <div class="form-group">
            <label>Datum</label>
            <input type="text" class="form-control" Name="Datum" value="@Model.Plata.Datum">
        </div>
        <label>Uposlenik</label>
        <select Name="UposlenikId">
            @foreach (var i in @Model.Uposlenici)
            {
                @if (@Model.Plata.UposlenikId == @i.Id)
                {
                    <option value="@i.Id" selected="selected">@i.ImePrezime</option>

                }
                else
                {
                    <option value="@i.Id">@i.ImePrezime</option>
                }

            }
        </select>
        
        <button type="submit" class="btn btn-primary">Sacuvaj</button>
    </form>
</div>