EAutoSkola/Models/Kategorija.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EAutoSkola.Models
{
    public class Kategorija
    {
        [Key]
        public int Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
       

    }
}

EAutoSkola/Controllers/KategorijaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EAutoSkola.Models;
using EAutoSkola.Models.Repository;
using EAutoSkola.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EAutoSkola.Controllers
{
    [Authorize(Roles = "Referent")]
    public class KategorijaController : Controller
    {
        private readonly IKategorijaRepository repo;
        private readonly IPotvrdaRepository reposPotvda;
        private readonly IUslugeRepository reposUsluga;
        private readonly IvozilaRepository reposVozilo;



        public KategorijaController(IKategorijaRepository repo, IPotvrdaRepository reposPotvda, IUslugeRepository reposUsluga, IvozilaRepository reposVozilo)
        {
            this.repo = repo;
            this.reposPotvda = reposPotvda;
            this.reposUsluga = reposUsluga;
            this.reposVozilo = reposVozilo;

        }

        public IActionResult DodajKategorijuForm()
        {
            return View();
        }
        public IActionResult PrikaziKategorije()
        {

            List<Kategorija> kategorije = repo.GetAll();
            var viewModel = new DefaultViewModel
            {
                Kategorije = kategorije
            };
            return View(viewModel);
        }
        public IActionResult UrediKategoriju(int KategorijaId)
        {

            Kategorija kategorija = repo.GetByID(KategorijaId);
            KategorijeViewModel kategorijaVM = new KategorijeViewModel()
            {
                Kategorija = kategorija
            };
            return View(kategorijaVM);
        }
        public IActionResult ObrisiKategoriju(int KategorijaId)
        {
            //Provera da li postoji zapis u drugim tabelama
            if (reposPotvda.Kategorija(KategorijaId) == true ||
                reposUsluga.Kategorija(KategorijaId) == true ||
                   reposVozilo.Kategorija(KategorijaId) == true
                 ) return View("Alert");
            Kategorija ka = repo.GetByID(KategorijaId);
            if (ka != null)
            {
                repo.Remove(ka);
            }
                        
            return RedirectToAction(nameof(PrikaziKategorije));
        }
        public IActionResult DodajUredjenuKategoriju(int KategorijaId, string Naziv, string Opis)
        {

            Kategorija k = repo.GetByID(KategorijaId);
            k.Naziv = Naziv;
            k.Opis = Opis;
            repo.Save();
            return RedirectToAction("PrikaziKategorije");
        }
        public IActionResult DodajKategoriju(string Naziv, string Opis)
        {

            Kategorija kat = new Kategorija();
            kat.Naziv = Naziv;
            kat.Opis = Opis;
            repo.Add(kat);
            return Redirect("/Kategorija/PrikaziKategorije");
        }
    }
}

EAutoSkola/Views/Kategorija/DodajKategorijuForm.cshtml
@{

    Layout = "_LayoutReferent";
}
<div class="divForme">
    <h2>Dodaj kategoriju</h2>
    <form class="Dodavanje" action="/Kategorija/DodajKategoriju">
        <div class="form-group">
            <label>Naziv</label>
            <input type="text" class="form-control" name="Naziv">
        </div>
        <div class="form-group">
            <label>Opis</label>
            <input type="text" class="form-control" name="Opis">
        </div>

        <button type="submit" class="btn btn-primary">Sacuvaj</button>
    </form>
 </div>

EAutoSkola/Views/Kategorija/PrikaziKategorije.cshtml
@model EAutoSkola.ViewModel.DefaultViewModel;
@{
    ViewBag.Title = "DodajKategorijuForm";
     Layout = "_LayoutReferent";
   
}

<h2 style=" color: #f9f9f9;
    border: 2px solid #f9f9f9;
    padding: 10px;
    background-color: #00c6ff">Kategorije</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Naziv</th>
            <th scope="col">Opis</th>
            <th></th>
        </tr>
    </thead>

    @foreach (var kategorija in Model.Kategorije)
    {
        <tbody>
            <tr>
                <td>@kategorija.Naziv</td>
                <td>@kategorija.Opis</td>
                <td><a asp-controller="Kategorija" asp-action="UrediKategoriju" asp-route-KategorijaId="@kategorija.Id" class="btn btn-primary">Uredi</a></td>
                <td><a asp-controller="Kategorija" asp-action="ObrisiKategoriju" asp-route-KategorijaId="@kategorija.Id" class="btn btn-danger">Obrisi</a></td>
            </tr>
        </tbody>
        }


</table>
<a asp-controller="Kategorija" asp-action="DodajKategorijuForm" class="btn btn-primary">Dodaj kategoriju</a>

EAutoSkola/Views/Kategorija/UrediKategoriju.cshtml
@model EAutoSkola.ViewModel.KategorijeViewModel;
@{
    ViewData["Title"] = "UrediKategoriju";
    Layout = "_LayoutReferent";
}
<div class="divForme">
    <h2>Uredite kategoriju</h2>
    <form action="/Kategorija/DodajUredjenuKategoriju">
        <input type="hidden" class="form-control" name="KategorijaId" value="@Model.Kategorija.Id">
        <div class="form-group">
            <label>Naziv</label>
            <input type="text" class="form-control" name="Naziv" value="@Model.Kategorija.Naziv">
        </div>
        <div class="form-group">
            <label>Opis</label>
            <input type="text" class="form-control" name="Opis" value="@Model.Kategorija.Opis">
        </div>
        <button type="submit" class="btn btn-primary">Sacuvaj</button>
    </form>
    </div>